from tkinter import *
window=Tk()
label=Label(window,text="CALCULATOR")

button1=Button(text="1",width="5",height='3')
button2=Button(text="2",width="5",height='3')
button3=Button(text="3",width="5",height='3')
button4=Button(text="4",width="5",height='3')
button5=Button(text="5",width="5",height='3')
button6=Button(text="6",width="5",height='3')
button7=Button(text="7",width="5",height='3')
button8=Button(text="8",width="5",height='3')
button9=Button(text="9",width="5",height='3')
button0=Button(text="0",width="5",height='3')
button_add=Button(text="+",width="5",height='3')
button_sub=Button(text="-",width="5",height='3')
button_mul=Button(text="*",width="5",height='3')
button_div=Button(text="/",width="5",height='3')
button_ent=Button(text="Enter",width="8",height='3')
button_bck=Button(text="<",width="5",height='3')
button_clr=Button(text="C",width="5",height='3')


button1.grid(row='0',column='0')
button2.grid(row='0',column='1')
button3.grid(row='0',column='2')
button4.grid(row='0',column='3')
button5.grid(row='0',column='4')
button6.grid(row='1',column='0')
button7.grid(row='1',column='1')
button8.grid(row='1',column='2')
button9.grid(row='1',column='3')
button0.grid(row='1',column='4')
button_add.grid(row='0',column='6')
button_sub.grid(row='0',column='7')
button_mul.grid(row='1',column='6')
button_div.grid(row='1',column='7')
button_clr.grid(row='2',column='0')
button_bck.grid(row='2',column='1')
button_ent.grid(row='2',column='3')




window.mainloop()
